testpress/ios-app

- ios-app/AppDelegate.swift
- ios-app/Model/AttemptSection.swift
- ios-app/Model/Course.swift
- ios-app/Network/TPEndpoint.swift
- ios-app/UI/TestEngineViewController.swift
- Change course API to 2.2.1
- Course API 2.2 is not being used anymore
> Change course API to 2.2.1

- ios-app/Network/TPEndpoint.swift
- ios-app/UI/RelatedContentsCell.swift
- ios-app/UI/VideoContentViewController.swift
- ios-app/ViewModel/VideoContentViewModel.swift
- Removed video content attempt update for every 3 seconds
- Video content attempt will be updated only when app goes to the background or user presses the back button
- Changed video content attempt API to 2.4 since 2.3 is depreciated
> Fix video content attempt for every 3 seconds

- ios-app/Views/VideoPlayerView.swift
- ios-appTests/Views/VideoPlayerViewTest.swift
- After changing playback speed if user pauses and again plays or minimizes and opens the app, the playback speed is reset.
- The above is because we use play method of AVPlayer which will reset playback speed to 1
- So now instead of directly using play method, we store current playback speed and whenever a video plays we use the stored playback speed
> Fix playback speed reset bug on minimize/play pause

- ios-app/Repository/EncryptionKeyRepository.swift
- Issue is we are storing encryption keys for each video in the keychain to reduce requests to server. But in backend if a video is retranscoded then, video url will be same but key will be different. So in that case iOS app won't fetch a new key as it has already stored key for the same video URL.
- So because of using incorrect encryption key, video is displayed as black.
> Fix video displayed as black issue

- ios-app.xcodeproj/project.pbxproj
- ios-app/AppDelegate.swift
- ios-app/Base.lproj/ChapterContent.storyboard
- ios-app/Model/Attachment.swift
- ios-app/UI/AttachmentDetailViewController.swift
- ios-appTests/ViewController/TestAttachmentDetailViewController.swift
- Download button should not be displayed for attachments that are renderable. 
- This is to prevent users from downloading and sharing attachments
> Hide download button for renderable attachments

- ios-app/Model/ApiError.swift
- ios-app/Model/TPError.swift
- ios-app/UI/TestEngineViewController.swift
- If server throws "max_attemptable_questions_limit_reached" then last attempted question should be cleared and error should be displayed to user that they have attempted maximum number of questions required for that section.
> Display error if user attends additional question in JEE exam

- ios-app/Model/BookmarksListResponse.swift
- ios-app/Network/BookmarksPager.swift
- We are not using steams which are obtained in bookmarks API so videos were not playing.
- This is fixed by storing streams from bookmarks API
> Fix bookmarked videos not playing bug

- ios-app/UI/BaseQuestionsPageViewController.swift
- ios-app/UI/TestEngineViewController.swift
- Issue is we while ending exam if max restriction on question error occurs then we are showing default exam error alert, which invalidates timer.
- This is fixed by showing Maximum question restrictions error dialog
- Another issue fixed is refreshing the same question view to unselect the selected options
> Fix end exam not working if max attendable questions is set

- ios-app.xcodeproj/project.pbxproj
- ios-app/AppDelegate.swift
- ios-app/Extensions/Collection.swift
- ios-app/Model/DRMLicenseKeyResponse.swift
- ios-app/Model/InstituteSettings.swift
- ios-app/Model/Streams.swift
- ios-app/Model/Video.swift
- ios-app/Network/TPEndpoint.swift
- ios-app/UI/DRMKeySessionDelegate.swift
- ios-app/UI/VideoContentViewController.swift
- ios-app/UI/VideoPlayerResourceLoaderDelegate.swift
- ios-app/Utils/M3U8Handler.swift
- ios-app/Views/VideoPlayerView.swift
- Added `fairplayCertificateUrl` in institute model
- When AVPlayer plays video, VideoPlayerResourceLoaderDelegate will check if key url is proper URL. Since DRM protected video's key url is not proper url (i.e skd:content_id), it will call DRMKeySessionDelegate's callback method.
- DRMKeySessionDelegate will create SPC (Secure playback context) request and POST it to license URL. License URL will return CKC (Content Key Context)
- CKC will be provided back to AVPlayer to play the video
> Support DRM protected video playback

- ios-app/UI/BaseQuestionsPageViewController.swift
- ios-app/UI/ReviewSolutionsViewController.swift
- The issue is while reviewing the questions after the attempt questions are not in order that students have attended the exam.
- This is fixed by showing the questions in the order that students have attempted on the review page.
> fix: Fix questions getting shuffled in the review page

- ios-app.xcodeproj/project.pbxproj
- ios-app/Extensions/Object.swift
- ios-app/UI/ChaptersViewController.swift
- We display chapters from local first and then once chapters from remote are fetched, we will delete all local chapters and store all values from remote.
- Issue is if user click any chapter instantly when all chapters are deleted then app is crashing with exception `RLMException’, reason: ‘Object has been deleted or invalidated.`
- This is fixed by using detached or deep copied objects instead of directly using reference objects from realmdb
- [Ref](https://github.com/realm/realm-swift/issues/5578)
> Fix app crash on opening chapters

- ios-app/UI/VideoPlayerResourceLoaderDelegate.swift
- As per [documentation](https://developer.apple.com/documentation/avfoundation/avassetresourceloadingcontentinformationrequest/2936886-allowedcontenttypes) we must set content type that was present in `AVAssetResourceLoadingContentInformationRequest.allowedContentTypes` on AVAssetResourceLoadingContentInformationRequest while setting encryption key response, otherwise it will raise NSInternalInconsistencyException which cause app crash.
> fix: Fix app crash on iOS 16 while playing video

- ios-app/UI/ZoomMeetViewController.swift
- This customer key parameter will be sent back when we access zoom reports, so we can use this to uniquely identify user
> fix: Send customer key to zoom join API

- ios-app/UI/VideoConferenceViewController.swift
- ios-app/Utils/FormatDate.swift
- The API sent UTC +0 and we displayed it as it is. As it leads to confusion among students, so display the start time in students' local time.
> fix: Display video conference start time in local time format

- ios-app/Utils/M3U8Handler.swift
- Issue is migrated institute's video encryption key was stored in a bucket and the relative path was mentioned in the m3u8 file unlike the video hosted in Testpress m3u8 file will have an API URL as the key URL, so we Faked that URL with a schema called "fakekeyhttps" to set the authorization header while making API call for the key.
- That faking wasn't done for migrated m3u8 file key URL so the app getting crashed while playing the video which was fixed in this commit.
> fix: App crash while playing migrated video

- ios-app/Core/Constants.swift
- ios-app/Core/Strings.swift
- ios-app/UI/ChaptersViewController.swift
- ios-app/UI/CourseTableViewCell.swift
- Currently, when the user clicks on the course we redirected the user to the contents table view if the courses don't have any chapters, which causes the app crash because in the ContentTableViewController we showed contents filtered by chapter id.
- This is fixed by showing the chapters table view where we set an empty view if the course doesn't have any chapter.
> fix: App crash while accessing empty course

- ios-app/AppDelegate.swift
- ios-app/Model/InstituteSettings.swift
- We used an invalid Sentry DSN while initializing the Sentry that's why app crash logs were not tracked, this is fixed by using DSN from the institute settings.
> fix: App crash logs not tracked in Sentry

- ios-app/AppDelegate.swift
- ios-app/UI/ZoomMeetViewController.swift
- Since we have updated zoom, by default full-screen is enabled for the waiting room, we don't need to do it separately and this code is causing some degradation in the meeting screen.
> chore: Remove zoom dead code

- ios-app/Model/Video.swift
- `URL` initializer will return nil if the given URL string contains non-ASCII this causes the app crash while playing the videos.
- This is fixed by encoding the URL string before creating a `URL` object from it.
- StackOverFlow [thread](https://stackoverflow.com/questions/49575034/url-in-diffrent-language-how-to-convert-a-url-in-swift).
> fix: Video not playing if its URL contains non-ascii characters

- Cartfile
- Cartfile.resolved
- ios-app.xcodeproj/project.pbxproj
- DropDown was not being maintained for last 3 years. So it is not supported in XCode 14.
- To support that package, it has to change minimum deployment target to 11
- Forked DropDown to our account(https://github.com/testpress/DropDown-Swift/) and changed minimum deployment target to 11
> Update dropdown package

- Cartfile
- Cartfile.resolved
- ios-app.xcodeproj/project.pbxproj
- We previously were using .framwork but latest master has .xcframework support
- Version 4.0.0 has an issue. It generates only IGListKit.xcframework. It is not building IGListDiffKit.xcframework.
- So we are using directly master itself in this commit
> Update IGListKit dependency to latest master

- ios-app/UI/DRMKeySessionDelegate.swift
- There were 2 bugs in the code
- One is contentID was not properly parsed. We are trying to type case content identifier("skd://<contend_id>") as string. But ideally it should be casted as url and then content id should be extracted from it.
- Another bug is DRM API failure. This is because we are adding Accept header which the server is rejecting.
> Fix DRM videos not playing bug

- ios-app/Utils/ImagePicker.swift
- Previously, when a user commented on a post, we would display an image picker dialog. If the user had not granted permission, we would request permission. This process would run on a background thread. If the user granted authorization, we needed to launch the camera to capture an image or show the selected file to choose an image. However, launching the camera was not possible from a background thread. In this commit, we have addressed this issue by ensuring that the camera is launched and the file selection for choosing an image is done on the main thread.
> fix: App crash on uploading image in comment on post 

- ios-app.xcodeproj/project.pbxproj
- ios-app/Extensions/UIInterfaceOrientationMask.swift
- ios-app/Extensions/UIViewController.swift
- ios-app/UI/VideoContentViewController.swift
- ios-app/Views/VideoPlayerView.swift
- The usage of UIDevice.current.setValue() specifically for screen rotation has been deprecated starting from iOS 16. Instead, for iOS 16 and newer versions, we now utilize requestGeometryUpdate() to achieve the same functionality. However, for iOS versions earlier than 16, we continue to rely on the old method setValue() for screen rotation.
> fix: Screen rotation not working on iOS versions 16 and higher.

- ios-app/AppDelegate.swift
- ios-app/Model/Exam.swift
- ios-app/UI/TestReportViewController.swift
- Analytics button is always showing because we did not handle this using showAnalytics field in the exam model
- Added showAnalytics filed in the exam model
- In this commit, we handled analyticsButtonLayout using showAnalytics field
> fix: Analytics button showing when Analytics is disable in exam settings

- ios-app/UI/ShareToUnlockViewController.swift
- Our application includes a feature called Growth Hack, which requires users to share a specific message with two individuals in order to view their exam results.
- On iPad, the alert will be displayed as a popover using the new UIPopoverPresentationController, it requires that you specify an anchor point for the presentation of the popover using sourceView - This is the reason for the crash
- App is working on iPhones because it has smaller screens compared to iPads, and the popover presentation style is not commonly used or supported on smaller devices.
> fix: App crash on iPad while clicking the button

- ios-app/Base.lproj/ExamReview.storyboard
- Previously we had the Solution button declared in the Analyts layout and the Time analytic button in the Solution layout. 
- So we are not able to handle the button visibility according to exam settings.
- However, in this commit, we have relocated the buttons to their respective layouts.
> fix: Replace Button to the respective layout

- ios-app/UI/TestReportViewController.swift
- Solution button is always showing because we did not handle this using showAnswers field in the exam model
- In this commit, we display the solution based on showAnswers field
> fix: Solution button showing when Soultions is disable in exam settings

- ios-app/UI/TestReportViewController.swift
- In this commit, we handled TestReportViewController without an exam object because the custom test generation feature does not contain an exam object.
> fix: Add support open exam review page without exam object

- ios-app/UI/BaseQuestionsPageViewController.swift
- ios-app/UI/BaseQuestionsSlidingViewController.swift
- ios-app/UI/StartExamScreenViewController.swift
- ios-app/UI/TestEngineViewController.swift
- ios-app/UI/TrophiesAchievedViewController.swift
- The custom test generation feature does not have an exam object but we need to take the exam in mobile template.
- So in this commit, we made the mobile exam template work without the exam object.
> fix: Add support to take exam without exam object

- ios-app/UI/WebViewController.swift
- If webview does not have back stack we cant close the webview viewcontroller
- In this commit, we fix this issue if webview dont have back stack we will close webview viewcontroller
> fix: Unable to Close WebView Controller without Back Stack

- ios-app/AppDelegate.swift
- ios-app/Model/ExamQuestion.swift
- ios-app/Repository/AttemptRepository.swift
- Added field `attemptId` in ExamQuestion model
- Previously we stored exam questions with examId
- Now we don't have an exam object for the custom test generation exam so we save the exam questions with attemptId and examId as null
- In this commit, we have implemented logic to retrieve a question from the database. If an examId is provided, we fetch the question associated with that examId; otherwise, we fetch the question using the attemptId.
> refactor: Add support for storing and fetching exam questions from the database using the attemptId

- ios-app/UI/CustomTestGenerationViewController.swift
- ios-app/UI/TestEngineViewController.swift
- Initially, The exam timer is not available for custom tests because it has infinite time.
- In this commit, we have introduced an exam time limit for custom tests. If the user selects a specific time, the exam timer will be displayed; otherwise, it remains hidden.
> fix: Add exam timer for custom test

- ios-app/UI/TestReportViewController.swift
- ios-app/Utils/TimeUtils.swift
- In this commit (dde8e6f), a timer for a custom test has been added. When the user finishes the exam, the report page is displayed without showing the total time.
- In this commit, we showcase the total time on the report page by adding both the `timeTaken` and `remainingTime` values in attempt.
> fix: Show total time in TestReport page

- ios-app/AppDelegate.swift
- ios-app/Model/Attempt.swift
- ios-app/Model/Exam.swift
- ios-app/UI/StartExamScreenViewController.swift
- We implemented a popup in this commit to allow users to select their preferred exam mode when starting an exam.
- When a user pauses an exam and later resumes it, we utilize the `attemptType` field to determine which mode the exam was originally started in. Based on this information, we appropriately resume the exam accordingly.
> feat: Add support take exams in quiz mode or regular mode

- ios-app/AppDelegate.swift
- ios-app/Model/Exam.swift
- This commit introduces the `selectedLanguage` and `languages` fields to the Exam.
- The `selectedLanguage` field indicates the language in which the user is taking the exam.
- The `languages` field provides a list of languages available for the exam.
> fix: Add `selectedLanguage` and `languages` fields in Exam model

- ios-app.xcodeproj/project.pbxproj
- ios-app/AppDelegate.swift
- ios-app/Model/AttemptAnswerTranslation.swift
- ios-app/Model/AttemptQuestion.swift
- ios-app/Model/AttemptQuestionTranslation.swift
- ios-app/Model/DirectionTranslation.swift
- In this commit, we Added the following models in DB.
- `AttemptAnswerTranslation`, `AttemptQuestionTranslation`, `DirectionTranslation`.
- And also we added the `AttemptQuestionTranslation` list field in `AttemptQuestion`.
> feat : Add Models in DB for Multiple language support in Exam

- ios-app/UI/CustomTestGenerationViewController.swift
- ios-app/UI/TestReportViewController.swift
- Previously when pressing the back button we navigated between the webview if it have a back stack.
- In this commit, the custom test view controller is closed when the user presses the back button.
> fix: Close Custom test view controller when user press the back button

- ios-app/UI/TestReportViewController.swift
- Previously, when the user closed the test report view controller we closed the custom test view controller too.
- With this commit, we no longer close the custom test view controller.
> fix: Prevent Custom test view controller closing

- ios-app/UI/TestReportViewController.swift
- When the user completes the custom test, we present the test report view controller.
- The inability to close the test report view controller because of the absence of a null check for presentingViewController.
> fix: Not able to close the Test report view controller

- ios-app/UI/TestEngineSlidingViewController.swift
- In this commit 05fc91e we added a language-switching option to exams.
- However, for custom test generation, there is no support for multiple languages. Therefore, we hide the language-switching button when the user takes a custom test.
> fix: Hide language switching button in custom test

- ios-app.xcodeproj/project.pbxproj
- ios-app/Base.lproj/ChapterContent.storyboard
- ios-app/Core/Constants.swift
- ios-app/UI/AttachmentDetailViewController.swift
- ios-app/UI/Dashboard/PDFViewController.swift
- In this commit, we replaced the `PDFReader` framework with `PDFKit`.
- Previously, when loading a PDF from a URL, the app would store it in RAM. If the PDF exceeded 300 MB, the app would run out of memory and crash.
- In this commit, we revised the approach to download and cache the PDF locally before passing it to the PDF viewer. This adjustment reduces RAM consumption.
> fix: App crash on open large pdf

- ios-app/AppDelegate.swift
- ios-app/Base.lproj/TestEngine.storyboard
- ios-app/Model/AttemptSection.swift
- ios-app/UI/TestEngineViewController.swift
- Introduced a new support that allows users to view section instructions during an attempt. 
- This feature is implemented by adding a button to the exam page. When users click on this button, instructions are displayed in a popup.
> fix: Support to view sections instructions during attempt

- ios-app/Model/Exam.swift
- ios-app/UI/TestEngineViewController.swift
- Sections dropdown was not displayed on the Exam page if any section did not have a duration.
- On Android and the Web, if any section lacks a duration, we switch to an unlocked section exam mode. This mode allows students to switch between sections without needing to end the current section. 
- Although we have this logic in our iOS app, an incorrect if condition was added, preventing the sections dropdown from appearing on the exam page.
- So corrected the if condition to ensure the Sections dropdown appears correctly.
> fix: Sections dropdown not shown in exam page

- ios-app/Info.plist
- In this commit, we are adding Privacy Usage Descriptions for `Contacts` and `Calendars`.
- The Zoom SDK uses these privacy options, and although our app doesn't utilize these features, The App Store Connect policy requires us to provide purpose strings explaining the use of these privacy options.
> fix: Add Privacy Usage Description for `Contacts` and `Calendars`.

- ios-app/UI/LiveStreamContentViewController.swift
- ios-app/Views/VideoPlayerView.swift
- The app was crashing when seeking in a live stream because AVPlayerItem returns an indefinite duration for live streams, causing incorrect seek calculations. 
- This commit fixes the issue by using a different method to obtain the live stream duration.
> fix: App crash while seeking the live using seek bar

- ios-app/Model/TPError.swift
- ios-app/UI/TestEngineViewController.swift
- Added a method to the TPError class for logging errors to Sentry
- Called this method on API failures occurring during exam attempts.
> fix: Log API failures during exam attempt in Sentry

- ios-app/AppDelegate.swift
- ios-app/Model/InstituteSettings.swift
- Implemented screen recording restriction for users when the institute disables screenshots in the app. 
- This commit only restricts screen recording, as it is not possible to prevent users from taking screenshots in an iOS app due to the lack of detection mechanisms.
> fix: Prevent screen recording the app

- ios-app/Utils/FileUploadPicker.swift
- Previously, files were uploaded for file type questions without setting the correct MIME type, defaulting to application/octet-stream for all files. 
- This caused the evaluate option to not appear for PDFs in the Testpress admin portal, as it only shows the option for content type application/pdf. This commit fixes the issue by setting the correct MIME type in the content type while uploading the file.
> fix: Set correct MIME type while file upload

- ios-app/Extensions/String.swift
- For section-based exams, a network error occurs when the first section ends due to incorrect time parsing.
- The remaining time is received in the format `0:00:00.000000` (including milliseconds).
- Our current parsing logic only handles the `0:00:00` format, resulting in the loss of seconds from the time string.
- This leads to an incorrect timer display and premature exam-ending attempt.
- Since these exams have section timers and prevent early section ending, the API call to end the section fails.
- By addressing the time parsing issue, we can prevent the network error and ensure correct exam behavior.
> fix: API failure on automatic section closure at end of duration

- ios-app/Core/Strings.swift
- ios-app/UI/TestEngineViewController.swift
- Previously, the preemptive section ending feature was not functioning correctly in the exam.
- Section switching is now handled based on the allowPreemptiveSectionEnding field.
- Updated the section locked message.
> fix: Preemptive Section Ending not working in Exam

- ios-app/Repository/EncryptionKeyRepository.swift
- ios-app/Utils/URLUtils.swift
- Previously, we used subdomain URLs (from the video manifest file) for encryption key requests. While this approach worked, it posed a problem if the institute changed its subdomain. In such cases, all video manifests needed to be updated on the backend, leading to videos not playing until the updates were made.
- This commit addresses the issue by using the institute's domain URL for encryption key requests, rather than the host specified in the video manifest file. This change avoids the need to update video manifests and ensures continuous video playback even if the institute's subdomain changes.
> fix: Use institute's domain URL for encryption key requests

- ios-app/Repository/EncryptionKeyRepository.swift
- ios-app/Utils/URLUtils.swift
- Previously, we used subdomain URLs (from the video manifest file) for encryption key requests. While this approach worked, it posed a problem if the institute changed its subdomain. In such cases, all video manifests needed to be updated on the backend, leading to videos not playing until the updates were made.
- This commit addresses the issue by using the institute's domain URL for encryption key requests, rather than the host specified in the video manifest file. This change avoids the need to update video manifests and ensures continuous video playback even if the institute's subdomain changes.
>  fix: Use institute's domain URL for encryption key requests

- Package.swift
- Update Swift tools version to 5.9 for Xcode compatibility.
- Correct "CourseKit" target path.
> fix: Path and Update swift tools version in `Package.swift`

- ios-app.xcodeproj/project.pbxproj
- ios-app/Extensions/DBModel+Detachable.swift
- ios-app/UI/BaseDBTableViewController.swift
- ios-app/UI/BaseDBTableViewControllerV2.swift
- ios-app/UI/BaseDBViewController.swift
- Replaced direct usage of Realm's Object with DBModel to eliminate Realm dependencies from the codebase.
- Moved detachment support from the Object extension to the DBModel class, ensuring the detachment functionality is preserved.
> refactor: Replace Realm Object Usage with DBModel

- ios-app.xcodeproj/project.pbxproj
- ios-app/AppDelegate.swift
- ios-app/Network/AuthErrorHandlingDelegate.swift
- ios-app/Network/TPApiClient.swift
- Refactored TPApiClient to implement AuthErrorHandlingDelegate, allowing  integration with the app's view controllers without tight coupling.
- This change is essential before moving TPApiClient to a package, as it allows the API client to operate independently while still handling authentication errors appropriately. Without this refactoring, the direct dependency on view controllers would hinder the migration.
> refactor: Modularize TPApiClient's Authentication Error Handling

- CourseKit/Source/TestpressCourse.swift
- Updated the `initialize` method to accept an optional JWT Auth token.
- The token is saved in the keychain for future use.
> fix: Allow passing JWT token on SDK initialization

- ios-app/UI/AccessCodeExamsViewController.swift
- ios-app/UI/AttemptsListViewController.swift
- ios-app/UI/ContentDetailPageViewController.swift
- ios-app/UI/ExamsTabViewController.swift
- ios-app/UI/TestEngineViewController.swift
- Refactored the `goBack` function in `TestEngineViewController` to remove direct dependencies on specific view controllers by introducing a new protocol to handle navigation logic and modified `goBack`, allowing more flexibility and reducing coupling.
- This refactor facilitates easier migration by decoupling the navigation behavior. With this change, we don't need to move tightly coupled controllers across modules.
> refactor: Decouple navigation logic from specific view controllers

- CourseKit/Source/Network/Models/TPError.swift
- Package.swift
- Removed the Sentry dependency when the package is integrated via Swift Package Manager (SPM). 
- This change addresses conflicts that occur when the package is used in environments where Sentry is already present for error logging (e.g., Yukthi Flutter app). 
- Also, using Sentry in a package or third-party plugin can lead to multiple Sentry instances, which is not advised. For more details check refs.
- Sentry integration has been conditionally removed only for SPM setups. The package is still used internally within our app, where Sentry remains necessary, and our app does not have Sentry as a separate dependency.
References:
- Sentry Documentation: https://docs.sentry.io/platforms/
- Related Sentry Issue: getsentry/sentry-docs#3611
> fix: Exclude Sentry dependency for SPM integrations

- CourseKit/Source/Database/DBManager.swift
- By default, the Realm SDK uses a default file path (`default.realm`) to store the Realm file. If an app using our package also has Realm as a dependency, both would attempt to use the same Realm file, leading to potential schema conflicts and improper migrations.
- Specifying a custom file path ensures that our package operates independently, avoiding conflicts with other Realm instances within the same app.
> fix: Specify custom Realm file path to prevent schema conflicts

- CourseKit/Source/Extensions/UIViewController.swift
- CourseKit/Source/TestpressCourse.swift
Previously, the primary color was used as the default for the status bar background. However, for Yukthi, the design requires a specific status bar color. This update adds support for configuring the status bar color during SDK initialization, allowing it to match the design requirements.
> fix: Add support to configure the status bar color

- CourseKit/Source/UI/ViewControllers/AttachmentDetailViewController.swift
- CourseKit/Source/UI/ViewControllers/AttemptsListViewController.swift
- CourseKit/Source/UI/ViewControllers/Base/BaseDBViewController.swift
- CourseKit/Source/UI/ViewControllers/Base/BaseTableViewController.swift
- CourseKit/Source/UI/ViewControllers/Base/BaseUIViewController.swift
- CourseKit/Source/UI/ViewControllers/Base/BaseWebViewController.swift
- CourseKit/Source/UI/ViewControllers/BaseQuestionsPageViewController.swift
- CourseKit/Source/UI/ViewControllers/BaseQuestionsSlidingViewController.swift
- CourseKit/Source/UI/ViewControllers/BookmarksDetailPageViewController.swift
- CourseKit/Source/UI/ViewControllers/ContentDetailPageViewController.swift
- CourseKit/Source/UI/ViewControllers/LiveStreamContentViewController.swift
- CourseKit/Source/UI/ViewControllers/LoadingViewController.swift
- CourseKit/Source/UI/ViewControllers/OverallSubjectAnalyticsViewController.swift
- CourseKit/Source/UI/ViewControllers/PDFViewController.swift
- CourseKit/Source/UI/ViewControllers/QuizExamViewController.swift
- CourseKit/Source/UI/ViewControllers/ShareToUnlockViewController.swift
- CourseKit/Source/UI/ViewControllers/StartExamScreenViewController.swift
- CourseKit/Source/UI/ViewControllers/StartQuizExamViewController.swift
- CourseKit/Source/UI/ViewControllers/TestReportViewController.swift
- CourseKit/Source/UI/ViewControllers/TimeAnalyticsTableViewController.swift
- CourseKit/Source/UI/ViewControllers/TrophiesAchievedViewController.swift
- CourseKit/Source/UI/ViewControllers/VideoConferenceViewController.swift
- CourseKit/Source/UI/ViewControllers/VideoContentViewController.swift
- CourseKit/Source/UI/ViewControllers/VideoPlayerViewController.swift
- ios-app.xcodeproj/project.pbxproj
- CourseKit view controllers did not support dark mode, which caused UI degradation when integrated into Flutter apps with dark themes.
- Introduced a BaseUIViewController class that enforces light mode by setting overrideUserInterfaceStyle to .light for all inheriting view controllers.
- Updated existing CourseKit view controllers to inherit from BaseUIViewController, ensuring a consistent light appearance.
> fix: Enforce light mode in CourseKit ViewControllers

- CourseKit/Source/UI/ViewControllers/OfflineDownloadTableViewCell.swift
- CourseKit/Source/UI/ViewControllers/OfflineDownloadsViewController.swift
This update adds the ability to play downloaded video content directly from the `OfflineDownloadsViewController`. A delegate pattern is implemented between `OfflineDownloadTableViewCell` and `OfflineDownloadsViewController` to handle cell interactions, allowing users to tap on an offline item and initiate playback in a full-screen player view.
> fix: Support video playback from offline downloads view

- CourseKit/Source/TestpressCourse.swift
- ios-app/UI/OfflineDownloadsTabController.swift
- Removed the `getOfflineDownloadsViewController()` method from TestpressCourse class.
- Replaced it with the `getMyDownloadsViewController()` method to provide access to the "Offline Downloads" screen.
> refactor: Offline Downloads View Controller Initialization

- ios-app.xcodeproj/project.pbxproj
- ios-app.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ios-app/UI/MainMenuTabViewController.swift
- Integrated Salesforce Marketing Cloud SDK to enable push notification capabilities.
- Added MarketingCloudSDK dependency in the iOS project via Swift Package Manager.
- Configured SDK initialization in MainMenuTabViewController with dynamic settings from instituteSettings.
- Implemented configureSalesforceSDK to handle push notification setup and error logging through Sentry.
> feat: Integrate Salesforce Marketing Cloud SDK for Enhanced Push Notifications

- CourseKit/Source/Database/Models/InstituteSettings.swift
- Added support for parsing the `is_video_download_enabled` field from the API and saving it in the database. 
- This ensures the video download button is displayed when the option is enabled.
> fix: Video download option not displayed

- ios-app/UI/Dashboard/SectionControllers/ChapterContentSectionController.swift
- App crashes when accessing content from the dashboard section due to incomplete content object relationships being passed to the content detail page view controller.
- The issue occurred because the dashboard response contains partial content data, and related objects were not available.
- Fixed by passing only contentId and letting the content detail page view controller fetch complete content data using its existing content loading logic.
> fix: App crash while accessing content from dashboard section

- CourseKit/Source/Database/DBManager.swift
- CourseKit/Source/Network/Pagers/ChapterPager.swift
- CourseKit/Source/TestpressCourse.swift
- CourseKit/Source/UI/ViewControllers/ChapterCollectionViewCell.swift
- CourseKit/Source/UI/ViewControllers/ChaptersViewController.swift
- CourseKit/Source/UI/ViewControllers/CourseTableViewCell.swift
- This PR addresses the inefficiency in fetching chapters for the chapter list. Previously, all chapters were fetched, and only the required root or child chapters were displayed to the user. This led to performance issues, especially with large datasets.
- Now fetching only the necessary chapters (root or child) from the database or API.
- The ChapterPager initialization is updated to pass only the relevant course ID and parent ID.
- The database fetch for chapters is now filtered by both courseId and parentId, ensuring only the necessary chapters are retrieved from the local database.
> fix: Optimize chapter fetching to load only required chapters

- CourseKit/Source/Utils/Constants.swift
- ios-app/UI/MoreOptionsViewController.swift
- ios-app/UI/ProfileViewController.swift
- ios-app/Utils/AppConstants.swift
- This PR refactors the application-specific constants (APP_APPLE_ID, APP_SHARE_MESSAGE, and APP_STORE_LINK) by moving them from the SDK's Constants struct to the app module's AppConstants struct.
- Separates SDK constants from app-specific configurations to enhance modularity and reusability.
- Ensures that app-specific constants are maintained within the app module, making future updates or customizations easier.
> refactor: Move app-specific constants from SDK to app module

- ios-app/AppDelegate.swift
- ios-app/UI/LoginViewController.swift
- ios-app/Utils/AppConstants.swift
Ensures the primary color is defined in a single location, making it easier to update or customize the app's theme.
> refactor: Move primary color constant to AppConstants for centralized configuration

- ios-app/UI/MainMenuTabViewController.swift
- This PR addresses an issue in MainMenuTabViewController where the Doubts screen was always appended to the view controllers list. The new behavior ensures the Doubts screen is added at index 3 if there are more than three view controllers; otherwise, it will be appended to the list.
- Previously, the Doubts WebViewController was always appended, leading to inconsistencies in its position. This fix ensures a consistent placement at index 3, aligning with the design expectations.
> fix: Add Doubts screen at index 3 or append if fewer view controllers

- ios-app.xcodeproj/project.pbxproj
- Previously, the Zoom Meeting SDK was included in the CourseKit library, which caused issues uploading the app to App Store Connect due to unsupported nested frameworks on iOS.
- This resolves the App Store upload issue by avoiding nested frameworks while maintaining Zoom SDK functionality at the host level.
> fix: Unable to upload App with Zoom dependency

- ios-app/Info.plist
- In this commit, we are adding Privacy Usage Descriptions for `Location`.
- The MarketingCloudSDK uses these privacy options, and although our app doesn't utilize these features, The App Store Connect policy requires us to provide purpose strings explaining the use of these privacy options.
> fix: Add Privacy Usage Description for Location.

- CourseKit/Source/Database/DBManager.swift
- CourseKit/Source/Repostories/InstituteRepository.swift
- ios-app/UI/LoginViewController.swift
- Previously, the `InstituteSettings` object was being refreshed in the background, causing crashes when accessing a deleted object. This update introduces an observer for `InstituteSettings`, ensuring that UI updates reflect the latest changes while preventing access to outdated objects. The observer updates the UI dynamically and properly handles object lifecycle changes.
> fix: Implement observer for InstituteSettings to prevent crashes

- ios-app/Utils/AuthErrorHandler.swift
- Previously, when a user encountered a parallel login error, they were redirected to the login screen without an option to log out. This update ensures that the login activity screen is shown instead, allowing users to log out properly before re-authenticating.
> fix: Show login activity screen on parallel login error

- ios-app/UI/LoginActivityViewController.swift
- The logout devices API returns an empty response, but our iOS TPApiClient handling mechanism treats an empty response as an error. Since this behavior is defined in the base class and cannot be changed, we handle it in the subclass (LoginActivityViewController). Now, upon receiving the response, we check the status code—if it is 200, we display a success message; otherwise, we show the error message from the API.
> fix: Show success message on parallel logout in LoginActivity
