testpress/ios-app

ios-app.xcodeproj/project.pbxproj, ios-app/Base.lproj/Main.storyboard, ios-app/UI/CourseTableViewCell.swift, ios-app/UI/CoursesTableViewController.swift, ios-app/UI/WebViewController.swift, ios-appTests/TestCourseViewController.swift
- Display external link label if the course contains an external link.
- On clicking course with an external label, webview will be opened
- For course which requires approval, the external link should be displayed in the web view.
- Number of Test Cases - 3
=> Display webview on external link click in course

ios-app.xcodeproj/project.pbxproj, ios-app/AppDelegate.swift, ios-app/Model/InstituteSettings.swift, ios-app/UI/MainMenuTabViewController.swift, ios-appTests/TestMainMenuTabViewController.swift, ios-appTests/TestUtils.swift
- Display activity feed based on institute settings
- Institutes can choose to display or hide activity feed easily.
- Number of Test Cases - 1
=> Honour institute settings for activity feed

ios-app.xcodeproj/project.pbxproj, ios-app/AppDelegate.swift, ios-app/Base.lproj/Main.storyboard, ios-app/Core/Strings.swift, ios-app/Extensions/Stackview+BackgroundColor.swift, ios-app/Model/InstituteSettings.swift, ios-app/UI/LoginActivityViewController.swift
- Add info if parallel login restriction is enabled
- By seeing this info user can know that parallel login restriction is enabled
=> Add parallel login restriction info

ios-app/Core/Strings.swift, ios-app/Model/InstituteSettings.swift, ios-app/Network/TPApiClient.swift
- Display alert on max login limit exceeded error.
- User can get insight if why the app is inaccessible.
=> Display alert on max login limit exceeded error

ios-app.xcodeproj/project.pbxproj, ios-app/Model/ContentAttempt.swift, ios-app/Model/VideoAttempt.swift, ios-app/Network/TPEndpoint.swift, ios-app/UI/ActivityFeedTableViewCell.swift, ios-app/UI/VideoContentViewController.swift, ios-app/ViewModel/VideoContentViewModel.swift, ios-app/Views/VideoPlayerView.swift
- Add support to update video attempt for every 3 seconds
=> Add support to create and update video attempt

ios-app.xcodeproj/project.pbxproj, ios-app/UI/VideoContentViewController.swift, ios-app/Views/VideoPlayerView.swift, ios-appTests/ViewController/TestVideoContentViewController.swift
- Show warning message if screen recording or external mirroring is being done
=> Disable screen recording and external mirroring

ios-app/Base.lproj/ChapterContent.storyboard, ios-app/UI/AttachmentDetailViewController.swift, ios-app/UI/BookmarkFolderTableViewController.swift, ios-app/UI/HtmlContentViewController.swift, ios-app/UI/ReviewQuestionsViewController.swift, ios-app/UI/VideoContentViewController.swift, ios-app/Utils/BookmarkHelper.swift
- Refactored bookmark helper to reuse it easily.
- Added delegates to easily bookmark/unbookmark
=> Refactor bookmark helper

ios-app/GoogleService-Info.plist, ios-app/UI/BookmarksDetailDataSource.swift, ios-app/UI/ContentDetailPageViewController.swift, ios-app/UI/RelatedContentsCell.swift, ios-app/UI/VideoContentViewController.swift
- Added functionality to bookmark/unbookmark related contents
=> Add support to bookmark related contents

ios-app.xcodeproj/project.pbxproj, ios-app/AppDelegate.swift, ios-app/Model/Streams.swift, ios-app/Model/Video.swift, ios-app/UI/ContentDetailPageViewController.swift, ios-app/UI/RelatedContentsCell.swift, ios-app/UI/VideoContentViewController.swift, ios-app/ViewModel/VideoContentViewModel.swift, ios-app/Views/VideoPlayerControlsView.swift, ios-app/Views/VideoPlayerSlider.swift, ios-app/Views/VideoPlayerView.swift, ios-app/Xib/VideoPlayerControls.xib
- Increased touch insets for Slider
- Reused video player for related contents
- Fixed video playing in the background bug
- Play HLS video
=> Bug fixes for video player

ios-app/Base.lproj/ExamReview.storyboard, ios-app/Base.lproj/Main.storyboard, ios-app/Model/Exam.swift, ios-app/UI/TestReportViewController.swift
- Lock exam solutions until user shares it two times if growth hacking is enabled.
=> Lock exam solutions until user shares

ios-app.xcodeproj/project.pbxproj, ios-app/AppDelegate.swift, ios-app/Base.lproj/ChapterContent.storyboard, ios-app/Core/Constants.swift, ios-app/Info.plist, ios-app/UI/ZoomMeetViewController.swift, ios-appTests/ViewController/TestZoomMeetViewController.swift
- Added ZoomMeetView controller which supports initializing and joining to zoom meeting
No of test cases - 6
=> Add view controller to initialise and join zoom meeting

ios-app.xcodeproj/project.pbxproj, ios-app/AppDelegate.swift, ios-app/Model/Content.swift, ios-app/Model/ContentsListResponse.swift, ios-app/Model/VideoConference.swift, ios-app/Network/ContentPager.swift
- Added video conference model
- Store video conference details from API
=> Added video conference model

ios-app.xcodeproj/project.pbxproj, ios-app/AppDelegate.swift, ios-app/Model/Course.swift, ios-app/UI/CoursesTableViewController.swift, ios-app/Utils/StringArrayTransform.swift
- Add support to display course list with specific tag
- This can be used if we want to display only courses which has specific tag
=> Add support to filter course by tags

ios-app.xcodeproj/project.pbxproj, ios-app/Model/Dashboard/DashboardResponse.swift, ios-app/UI/Dashboard/CarouselCellViews/BannerAdViewCell.swift, ios-app/UI/Dashboard/CarouselCellViews/BannerAdViewCell.xib, ios-app/UI/Dashboard/CarouselCellViews/HorizontalSectionCell.swift, ios-app/UI/Dashboard/SectionControllers/BannerSectionController.swift, ios-app/UI/Dashboard/SectionControllers/CarouselSectionController.swift, ios-app/UI/DashboardViewController.swift
- Added banner ads section to dashboard
=> Add banner ad section to dashboard

ios-app/AppDelegate.swift, ios-app/Model/Content.swift, ios-app/UI/ContentsTableViewCell.swift
- Displayed lock symbol and completed info for completed contents
- Also disable click for completed contents
=> Display lock symbol and info for completed contents

ios-app/AppDelegate.swift, ios-app/Model/AttemptItem.swift, ios-app/Model/AttemptQuestion.swift, ios-app/Network/TPApiClient.swift, ios-app/Repository/AttemptItemRepository.swift, ios-app/UI/QuestionsViewController.swift, ios-app/UI/ReviewQuestionsViewController.swift, ios-app/UI/TestEngineViewController.swift, ios-app/static/TestEngine.js, ios-app/static/questions_typebase.css
- Added essay type question support
=> Add Essay type question support

ios-app.xcodeproj/project.pbxproj, ios-app/Base.lproj/Main.storyboard, ios-app/Extensions/Misc.swift, ios-app/UI/ForumTableViewController.swift, ios-app/UI/ForumViewController.swift
- Added search bar to discussions view controller.
- When user types text in search bar existing discussions will be cleared and API call will be made for searched discussions
=> Add search functionality to discussions

ios-app.xcodeproj/project.pbxproj, ios-app/Base.lproj/Post.storyboard, ios-app/Model/DiscussionThreadAnswer.swift, ios-app/Model/Post.swift, ios-app/UI/DiscussionThreadDetailViewController.swift, ios-app/UI/ForumTableViewCell.swift, ios-app/UI/PostDetailViewController.swift
- Display accepted answer in discussions
=> Display accepted answer in discussions

ios-app.xcodeproj/project.pbxproj, ios-app/Base.lproj/ChapterContent.storyboard, ios-app/Extensions/Misc.swift, ios-app/Extensions/String.swift, ios-app/UI/VideoContentViewController.swift, ios-app/Utils/TimeUtils.swift, ios-app/ViewModel/VideoContentViewModel.swift
- Added support to make video duration clickable in video description
- Following Regex are supported
- HH:MM:SS
- H:MM:SS
- MM:SS
- M:SS
=> Enable go to video duration in video description

ios-app/UI/BaseDBTableViewControllerV2.swift, ios-app/UI/ContentsTableViewController.swift
- Issue is removed contents are shown to students because contents that are removed from the course still exist in the local cache which was not cleared before loading new data, fixed the same in this commit.
=> fix: Fix removed contents shown to students in content list page

ios-app/AppDelegate.swift, ios-app/Base.lproj/Main.storyboard, ios-app/Model/InstituteSettings.swift, ios-app/UI/LoginViewController.swift
- Added disableForgotPassword field to the institute settings DB.
- Showed forgot password button based on institute settings.
=> fix: Show forgot password button based on institute settings

Cartfile, Cartfile.resolved, ios-app.xcodeproj/project.pbxproj, ios-app/Network/TPApiClient.swift
- Used AF constant of Alamofire to access its methods
- Previously we used to build uploadRequest and then make request. But now we can directly make upload request
=> fix: Update Alamofire to 5.0.2

ios-app.xcodeproj/project.pbxproj
-To make the application work in real devices we need to add Dependency frameworks to Embed Frameworks
=> fix: App not working Real device

ios-app/Model/Attempt.swift, ios-app/UI/TestReportViewController.swift
- Extract meaning full method
- Follow stepdown rule
=> refcator: TestReportViewController

ios-app/UI/WebViewController.swift
- Remove Unused Javascript interface in WebViewController
=> refactor: Remove unused code in WebViewController

ios-app/UI/TestEngineViewController.swift
- Extract meaning full method TestEngineViewController
=> refactor: Extract meaning full methods

ios-app/Model/Language.swift
- In the Realm database if we have to modify the data in runtime we need to declare the variable with dynamic attributes [Docs](https://www.mongodb.com/docs/realm/sdk/swift/model-data/object-models/#objective-c-dynamic-property-attributes)
=> fix: Language not selecting for the first time

ios-app/Base.lproj/Main.storyboard, ios-app/UI/ProfileViewController.swift, ios-app/UI/WebViewController.swift
- Added support for updating user profiles. This includes adding an 'edit' option to the navigation bar on the profile page and displaying the profile edit page in a web view.
=> fix: Add support to update user profile

ios-app.xcodeproj/project.pbxproj, ios-app/AppDelegate.swift, ios-app/Model/Content.swift, ios-app/Model/ContentsListResponse.swift, ios-app/Model/LiveStream.swift, ios-app/Network/ContentPager.swift
- Added realm model to store live stream content details.
- Stored the Live stream content network response in the created DB.
=> fix: Store Live stream network response in model

ios-app/Base.lproj/ChapterContent.storyboard, ios-app/UI/LiveStreamContentViewController.swift, ios-app/UI/WebViewController.swift
- Refactored WebViewController to support loading both URL and URLRequest by adding a URLRequest property and updating the loadWebView method, allowing requests with extra headers.
- Showed the live chat view in the web view below the video player using the chat embed URL.
=> feat: Show live chat embed view in live stream detail page

ios-app/UI/ContentDetailDataSource.swift, ios-app/UI/LiveStreamContentViewController.swift
- Created Chapter content attempt when user joins the live stream.
=> feat: Create Content attempt when user joins live stream

ios-app/Views/VideoPlayerControlsView.swift, ios-app/Views/VideoPlayerView.swift, ios-app/Xib/VideoPlayerControls.xib
- Displayed the Live label in the player instead of the total duration by adding a UI container to the player controls view. If the player is used for live streaming, the Live label is added programmatically inside this container.
=> fix: Display Live label in player for live stream

ios-app/UI/QuestionsViewController.swift, ios-app/static/TestEngine.js
- Extract code into methods with meaningful names
- Include answer type in input message events to handle user input more cleanly
=> refactor: Refactor Question view controller

ios-app/Model/AttemptItem.swift
- Fixed the issue where user-uploaded files weren't displayed on the file question page when resuming the exam by storing details of user-uploaded files from the network as initial values in `localFiles` to store. 
- This change ensures that the question page automatically shows that files have been uploaded and provides the option to clear them.
- Added transformer for `UserFileResponse` to handle different API responses for user-uploaded details, which can be either a list of strings (file paths) or a list of JSON objects (`UserFileResponse`).
=> Fix: Uploaded files not showing on iOS exam resume

ios-app/UI/ReviewQuestionsViewController.swift
- Refactored the Question review view controller by extracting long functions into smaller function with meaningful name.
=> refactor: Review question view controller

ios-app.xcodeproj/project.pbxproj, ios-app/AppDelegate.swift, ios-app/Model/FileResponse.swift, ios-app/UI/ReviewQuestionsViewController.swift, ios-app/Utils/FileDownloadUtility.swift, ios-app/Utils/WebViewUtils.swift, ios-app/static/QuestionReviewPage.js, ios-app/static/TestEngine.js, ios-app/static/questions_typebase.css
- Added support to preview or download the user uploaded file for file type question in the attempt review page.
=> feat: Support to preview/download uploaded file

CourseKit/CourseKit.docc/CourseKit.md, CourseKit/CourseKit.h, CourseKit/Source/StoryBoards/Course.storyboard, CourseKit/Source/TestpressCourse.swift, CourseKit/Source/ViewControllers/ContentDetailViewController.swift, CourseKit/Source/ViewControllers/CourseListViewController.swift, CourseKitTests/CourseKitTests.swift, Package.swift, ios-app.xcodeproj/project.pbxproj
- Created the CourseKit package to serve as a stub for Flutter integration.
- Implemented dummy views to facilitate initial development and testing.
- Configured the package for Swift Package Manager (SPM) deployment.
=> Add CourseKit package with dummy views for Flutter integration

CourseKit/Source/TestpressCourse.swift
- Updated the CourseKit package methods to return view controllers instead of presenting them directly.
- This change enhances flexibility, allowing the caller to choose how and when to present the view controllers.
=> fix: Return view controllers instead of presenting them directly

CourseKit/Source/TestpressCourse.swift, ios-app/AppDelegate.swift, ios-app/Utils/UIUtils.swift
- Added initialize method to handle DBConnection.configure() for setting up the database.
- Added clearData method to handle DBConnection.clearTables() for cleanup.
- Updated app to call these methods, removing direct use of DBConnection in the app.
=> refactor: Encapsulate DBConnection setup and cleanup

CourseKit/Source/TestpressCourse.swift, CourseKit/Source/ViewControllers/ContentDetailPageViewController.swift
- Added support to get the content detail page view controller via CourseKit.
- Modified ContentDetailPageViewController to allow initialization and presentation using the content ID alone.
=> feat: Support to get content detail view controller via CourseKit

ios-app.xcodeproj/project.pbxproj, ios-app/AppDelegate.swift, ios-app/Utils/AppConstants.swift
- Created a new AppConstants.swift file under Utils to define app-wide constants.
=> enhancement: Add AppConstants file to centralize app configuration

CourseKit/Source/TestpressCourse.swift, CourseKit/Source/UI/StoryBoards/Course.storyboard, CourseKit/Source/UI/ViewControllers/OfflineDownloadTableViewCell.swift, CourseKit/Source/UI/ViewControllers/OfflineDownloadsViewController.swift, CourseKit/Source/UI/ViewControllers/VideoContentViewController.swift, CourseKit/Source/Utils/Constants.swift, CourseKit/Source/Utils/TimeUtils.swift, ios-app.xcodeproj/project.pbxproj, ios-app/Base.lproj/Main.storyboard, ios-app/UI/OfflineDownloadsTabController.swift
- In this commit, we added the Offline Download List view along with options to cancel and delete downloads directly from the list.
=> feat: App Offline Download list view

CourseKit/Source/UI/ViewControllers/VideoContentViewController.swift, ios-app.xcodeproj/project.pbxproj, ios-app.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Implemented a check to validate if the video asset is available offline before initializing the player, ensuring smooth offline playback.
=> fix: Support for playing videos from local storage if available

CourseKit/Source/TestpressCourse.swift, CourseKit/Source/UI/ViewControllers/CoursesTableViewController.swift
- Adds methods in TestpressCourse and properties in CoursesTableViewController to filter courses by tags or exclude courses with excludeTags. Updates the getItems() logic to support these filters for more dynamic course retrieval.
=> feat: add support for filtering courses by tags and exclude tags

CourseKit/Source/Utils/Images.swift, ios-app/Base.lproj/Main.storyboard, ios-app/UI/MainMenuTabViewController.swift
This PR replaces the old native Discussions UI with a new WebView-based Discussions UI, streamlining the code and providing a more consistent, web-based experience for the user.
=> enhancement: Replace old Discussions UI with new WebView Discussions UI

CourseKit/Source/UI/ViewControllers/VideoConferenceViewController.swift, CourseKit/Source/UI/ViewControllers/ZoomMeetViewController.swift, ios-app.xcodeproj/project.pbxproj, ios-app/UI/MainMenuTabViewController.swift
- Enabled Zoom SDK by Default
- Upgraded the Zoom SDK to version 6.3.5.21766 for enhanced stability and functionality.
- Removed redundant logic for setting the root view controller.
- Eliminated unnecessary tab view controller initialization on back button press.
=> enhancement: Update Zoom SDK to version 6.3.5.21766

ios-app.xcodeproj/project.pbxproj, ios-app/GoogleService-Info.plist, ios-app/Info.plist
- Renamed the app to Testpress LMS.
- Added the Google services configuration file.
- Increased the iOS app version to 3.0.0.
=> fix: Update to version 3.0.0 release

ios-app.xcodeproj/project.pbxproj
\- Increased iOS app version from 3.0.0 to 3.0.1
=> fix: Increased App version to 3.0.1

ios-app.xcodeproj/project.pbxproj
- Increased iOS app version from 3.0.1 to 3.0.2
=> fix: Increased App version to 3.0.2
